import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";
import { data, money, nextId } from "../shop.js";

const composer = new Composer<Ctx>();
const panel = () => inlineKeyboard([[inlineButton("Categories", "admin:categories"), inlineButton("Products", "admin:products")], [inlineButton("Orders", "admin:orders"), inlineButton("Referral rules", "admin:referrals")]]);
async function owner(ctx: Ctx): Promise<boolean> { return requireOwner(ctx as never); }

composer.command("admin", async (ctx) => { if (!(await owner(ctx))) return; await ctx.reply("Owner controls", { reply_markup: panel() }); });
composer.callbackQuery(/^admin:(categories|products|orders|referrals)$/, async (ctx) => {
  await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const section = ctx.match[1]; const shop = data(ctx);
  if (section === "categories") { const items = shop.categoryIds.map((id) => shop.categories[id]).filter(Boolean); await ctx.editMessageText(items.length ? `Categories\n${items.map((c) => c.title).join("\n")}` : "No categories yet. Add one to start your catalog.", { reply_markup: inlineKeyboard([[inlineButton("Add category", "admin:category:add")], ...items.map((c) => [inlineButton(`Edit ${c.title}`, `admin:category:edit:${c.id}`), inlineButton("Remove", `admin:category:remove:${c.id}`)]), [inlineButton("Back", "admin:panel")]]) }); return; }
  if (section === "products") { const items = shop.productIds.map((id) => shop.products[id]).filter(Boolean); await ctx.editMessageText(items.length ? `Products\n${items.map((p) => `${p.name} — ${p.stock_qty} in stock${p.visible ? "" : " (hidden)"}`).join("\n")}` : "No products yet. Add a category, then add a product.", { reply_markup: inlineKeyboard([[inlineButton("Add product", "admin:product:add")], ...items.flatMap((p) => [[inlineButton(`${p.name}: stock`, `admin:stock:${p.id}`), inlineButton(p.visible ? "Hide" : "Show", `admin:visible:${p.id}`)], [inlineButton(`Edit ${p.name}`, `admin:product:edit:${p.id}`), inlineButton("Remove", `admin:product:remove:${p.id}`)]]), [inlineButton("Back", "admin:panel")]]) }); return; }
  if (section === "orders") { const orders = shop.orderIds.map((id) => shop.orders[id]); await ctx.editMessageText(orders.length ? `Orders\n${orders.map((o) => `${o.id} — ${money(o.total)} — ${o.status}`).join("\n")}` : "No orders yet.", { reply_markup: inlineKeyboard([...orders.map((o) => [inlineButton(`${o.id}: next status`, `admin:order:${o.id}`)]), [inlineButton("Back", "admin:panel")]]) }); return; }
  await ctx.editMessageText(`First-order referral credit: ${shop.referralRules.firstOrderCredit.toFixed(2)} zł`, { reply_markup: inlineKeyboard([[inlineButton("Change credit", "admin:reward")], [inlineButton("Back", "admin:panel")]]) });
});
composer.callbackQuery("admin:panel", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; await ctx.editMessageText("Owner controls", { reply_markup: panel() }); });
composer.callbackQuery("admin:category:add", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.flow = { kind: "admin_category" }; await ctx.editMessageText("Send the category as: title | description"); });
composer.callbackQuery(/^admin:category:edit:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; if (!data(ctx).categories[ctx.match[1]]) { await ctx.editMessageText("That category no longer exists."); return; } ctx.session.flow = { kind: "admin_category_edit", value: ctx.match[1] }; await ctx.editMessageText("Send the category as: title | description"); });
composer.callbackQuery(/^admin:category:remove:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const shop = data(ctx); const id = ctx.match[1]; const category = shop.categories[id]; if (!category) { await ctx.editMessageText("That category no longer exists."); return; } if (shop.productIds.some((productId) => shop.products[productId]?.category === id)) { await ctx.editMessageText("Remove or move this category's products before removing it."); return; } delete shop.categories[id]; shop.categoryIds = shop.categoryIds.filter((categoryId) => categoryId !== id); await ctx.editMessageText(`${category.title} was removed.`, { reply_markup: inlineKeyboard([[inlineButton("Categories", "admin:categories")]]) }); });
composer.callbackQuery("admin:product:add", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; if (!data(ctx).categoryIds.length) { await ctx.editMessageText("Add a category before adding a product."); return; } ctx.session.flow = { kind: "admin_product" }; await ctx.editMessageText("Send the product as: name | SKU | price in zł | stock quantity | category title | description"); });
composer.callbackQuery(/^admin:product:edit:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; if (!data(ctx).products[ctx.match[1]]) { await ctx.editMessageText("That product no longer exists."); return; } ctx.session.flow = { kind: "admin_product_edit", value: ctx.match[1] }; await ctx.editMessageText("Send the product as: name | SKU | price in zł | stock quantity | category title | description"); });
composer.callbackQuery(/^admin:product:remove:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const shop = data(ctx); const id = ctx.match[1]; const p = shop.products[id]; if (!p) { await ctx.editMessageText("That product no longer exists."); return; } delete shop.products[id]; shop.productIds = shop.productIds.filter((productId) => productId !== id); for (const key of Object.keys(shop.carts)) shop.carts[key] = shop.carts[key].filter((line) => line.productId !== id); await ctx.editMessageText(`${p.name} was removed.`, { reply_markup: inlineKeyboard([[inlineButton("Products", "admin:products")]]) }); });
composer.callbackQuery(/^admin:stock:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.flow = { kind: "admin_stock", value: ctx.match[1] }; await ctx.editMessageText("Send the new stock quantity as a whole number."); });
composer.callbackQuery(/^admin:visible:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const p = data(ctx).products[ctx.match[1]]; if (!p) { await ctx.editMessageText("That product no longer exists."); return; } p.visible = !p.visible; await ctx.editMessageText(`${p.name} is now ${p.visible ? "visible" : "hidden"}.`, { reply_markup: inlineKeyboard([[inlineButton("Products", "admin:products")]]) }); });
composer.callbackQuery("admin:reward", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; ctx.session.flow = { kind: "admin_reward" }; await ctx.editMessageText("Send the first-order referral credit in zł."); });
composer.callbackQuery(/^admin:order:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await owner(ctx))) return; const order = data(ctx).orders[ctx.match[1]]; if (!order) { await ctx.editMessageText("That order no longer exists."); return; } const statuses: typeof order.status[] = ["new", "preparing", "ready", "completed", "cancelled"]; order.status = statuses[(statuses.indexOf(order.status) + 1) % statuses.length]; await ctx.editMessageText(`${order.id} is now ${order.status}.`, { reply_markup: inlineKeyboard([[inlineButton("Orders", "admin:orders")]]) }); });
composer.on("message:text", async (ctx, next) => {
  const flow = ctx.session.flow; if (!flow || !flow.kind.startsWith("admin_")) return next(); if (!(await owner(ctx))) return;
  const input = ctx.message.text.trim(); const shop = data(ctx);
  if (flow.kind === "admin_category" || flow.kind === "admin_category_edit") { const [title, description] = input.split("|").map((part) => part.trim()); if (!title || !description) { await ctx.reply("Use: title | description"); return; } const id = flow.kind === "admin_category_edit" ? flow.value : nextId(shop, "category-"); const old = id ? shop.categories[id] : undefined; if (!id || (flow.kind === "admin_category_edit" && !old)) { await ctx.reply("That category no longer exists."); return; } shop.categories[id] = { id, title, description, order: old?.order ?? shop.categoryIds.length + 1 }; if (!old) shop.categoryIds.push(id); ctx.session.flow = undefined; await ctx.reply(`${title} was ${old ? "updated" : "added"}.`, { reply_markup: inlineKeyboard([[inlineButton("Categories", "admin:categories")]]) }); return; }
  if (flow.kind === "admin_product" || flow.kind === "admin_product_edit") { const parts = input.split("|").map((part) => part.trim()); const price = Number(parts[2]); const stock = Number(parts[3]); const category = shop.categoryIds.map((id) => shop.categories[id]).find((c) => c?.title.toLowerCase() === parts[4]?.toLowerCase()); if (parts.length !== 6 || !parts[0] || !parts[1] || !Number.isFinite(price) || price < 0 || !Number.isInteger(stock) || stock < 0 || !category) { await ctx.reply("Use: name | SKU | price in zł | stock quantity | category title | description. The category must already exist."); return; } const id = flow.kind === "admin_product_edit" ? flow.value : nextId(shop, "product-"); const old = id ? shop.products[id] : undefined; if (!id || (flow.kind === "admin_product_edit" && !old)) { await ctx.reply("That product no longer exists."); return; } shop.products[id] = { id, name: parts[0], sku: parts[1], price: Math.round(price * 100), category: category.id, stock_qty: stock, excise_flag: old?.excise_flag ?? true, images: old?.images ?? [], description: parts[5], visible: old?.visible ?? true }; if (!old) shop.productIds.push(id); ctx.session.flow = undefined; await ctx.reply(`${parts[0]} was ${old ? "updated" : "added and is visible"}.`, { reply_markup: inlineKeyboard([[inlineButton("Products", "admin:products")]]) }); return; }
  if (flow.kind === "admin_stock") { const stock = Number(input); const p = flow.value ? shop.products[flow.value] : undefined; if (!p || !Number.isInteger(stock) || stock < 0) { await ctx.reply("Send a whole stock quantity of zero or more."); return; } p.stock_qty = stock; ctx.session.flow = undefined; await ctx.reply(`${p.name} now has ${stock} in stock.`, { reply_markup: inlineKeyboard([[inlineButton("Products", "admin:products")]]) }); return; }
  const credit = Number(input); if (!Number.isFinite(credit) || credit < 0) { await ctx.reply("Send a credit amount of zero or more."); return; } shop.referralRules.firstOrderCredit = Math.round(credit * 100) / 100; ctx.session.flow = undefined; await ctx.reply(`First-order referral credit is now ${shop.referralRules.firstOrderCredit.toFixed(2)} zł.`, { reply_markup: inlineKeyboard([[inlineButton("Referral rules", "admin:referrals")]]) });
});
export default composer;
